### ISSUE TITLE
Rules and input in sub-directory doesn't work

### ISSUE THREAD

**Issue by mhausenblas** [open-policy-agent/vscode-opa#27]
I'm working on [mhausenblas/eunomia/](https://github.com/mhausenblas/eunomia/tree/master/test) and when I issue the query on the command line, in the respective sub-dir I get the expected result:

```
opa eval --input input.json --data violations.rego --package violations.eunomia.testing 'rbac_cluster_role'
```
However, with the VSCode plug-in I get:

```
// Evaluated package in 763.04µs.
{
  "rbac_cluster_role": []
}
```

I tried to set `opa.roots` in `settings.json` to `${fileDirname}` but that didn't help either.

**Comment by patrick-east** [comment]
I think things are working as intended.

The VSCode integration current looks at the workspace root for a file called `input.json` which it will use as the input for evaluations. If you open vscode only on the `./test` directory it works as expected, for example:

![image](https://user-images.githubusercontent.com/3614287/76358564-e2740880-62d6-11ea-9e60-5964c03cd5ca.png)

![image](https://user-images.githubusercontent.com/3614287/76358582-eb64da00-62d6-11ea-80ff-13d171059409.png)

What would be helpful is if we could adjust the plugin tasks to allow providing a different/custom input document. That seems like the right way to make this work more as expected (along with https://github.com/open-policy-agent/vscode-opa/issues/26 so that its easier to see what actually was being run)


In the meantime for your project you can always just make custom VSCode tasks like:

`.vscode/tasks.json`:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "eval rbac_cluster_role",
            "type": "shell",
            "command": "opa eval --input ./test/input.json --data ./test/violations.rego --package violations.eunomia.testing rbac_cluster_role"
        }
    ]
}
```

Which you can invoke via the command pallete
![image](https://user-images.githubusercontent.com/3614287/76361318-00903780-62dc-11ea-8477-675bce32eb5d.png)

And get your results in vscode:
![image](https://user-images.githubusercontent.com/3614287/76361402-39c8a780-62dc-11ea-867b-3e207e60076f.png)

**Comment by patrick-east** [comment]
I filed https://github.com/open-policy-agent/vscode-opa/issues/28 to track adding some way to provide custom input paths.

**Comment by mhausenblas** [comment]
Thanks a million for the very speedy follow up and resolution, really appreciate it @patrick-east ... I shall subscribe to #28 ;)
